const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite'),{webcrypto,randomUUID}=require('node:crypto'),ts=require('typescript');
const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE submissions (id TEXT PRIMARY KEY,role TEXT,question TEXT,created_at INTEGER,client_hash TEXT,name TEXT,email TEXT,email_status TEXT DEFAULT "pending")');
let now=Date.parse('2026-09-18T23:59:00Z'),notified=0;
const db={prepare(query){return {bind(...args){return {async first(){return sql.prepare(query).get(...args)||null},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:r.changes}}}}}}}};
function load(file,requireFn,extra={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:requireFn,Response,Request,URL,crypto:webcrypto,TextDecoder,TextEncoder,Uint8Array,console,Date:class extends Date{static now(){return now}},AbortSignal,...extra});return exports;}
const route=load('app/api/questions/route.ts',n=>n.includes('verify-human')?{verifyHuman:async()=> 'ok'}:n.includes('/inbox')?{inbox:()=>db}:n.includes('notify-owner')?{notifyOwner:async()=>{notified++}}:{default:{}});
function request(change={},headers={},body){return new Request('https://example.test/api/questions',{method:'POST',headers:{Origin:'https://example.test','Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1',...headers},body:body??JSON.stringify({id:randomUUID(),name:'QA Test',email:'qa@example.test',role:'project-manager',question:'How do you handle project prioritization?',...change})});}
let passed=0;function pass(s){passed++;console.log('PASS '+s)}
function reset(){sql.exec('DELETE FROM submissions');notified=0;now=Date.parse('2026-09-18T23:59:00Z')}
(async()=>{
for(const change of [{name:''},{email:''},{email:'bad'},{role:'admin'},{id:'bad'},{question:'short'},{website:'spam'}])assert.equal((await route.POST(request(change))).status,400);pass('Required fields, IDs, role, question bounds and honeypot');
assert.equal((await route.POST(request({}, {Origin:'https://evil.test'}))).status,403);
const noOrigin=request();noOrigin.headers.delete('origin');assert.equal((await route.POST(noOrigin)).status,403);
assert.equal((await route.POST(request({}, {'Sec-Fetch-Site':'cross-site'}))).status,403);pass('Cross-site and missing-origin rejection');
assert.equal((await route.POST(request({}, {'Content-Type':'text/plain'}))).status,415);
assert.equal((await route.POST(request({}, {},'{broken'))).status,400);
assert.equal((await route.POST(request({}, {},'x'.repeat(10001)))).status,413);pass('Malformed and oversized bodies rejected');
const noIP=request();noIP.headers.delete('cf-connecting-ip');assert.equal((await route.POST(noIP)).status,503);pass('Missing trusted network header fails closed');
reset();for(let i=0;i<3;i++)assert.equal((await route.POST(request())).status,201);
let r=await route.POST(request());assert.equal(r.status,429);assert.equal(r.headers.get('Retry-After'),'86400');assert.equal(notified,3);pass('First 3 saved; fourth rejected with retry time and no notification');
now+=120000;assert.equal((await route.POST(request())).status,429);pass('Midnight does not reset quota');
now+=86400000-120001;assert.equal((await route.POST(request())).status,429);now+=1;assert.equal((await route.POST(request())).status,201);pass('Blocked until exactly 24 hours, then allowed');
reset();for(let i=0;i<3;i++)await route.POST(request());assert.equal((await route.POST(request({email:'QA@EXAMPLE.TEST'},{'CF-Connecting-IP':'192.0.2.2'}))).status,429);assert.equal((await route.POST(request({email:'other@example.test'}))).status,429);pass('Email case/new IP and changed email/same IP do not reset quota');
reset();const batch=await Promise.all(Array.from({length:12},()=>route.POST(request())));assert.equal(batch.filter(x=>x.status===201).length,3);assert.equal(batch.filter(x=>x.status===429).length,9);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM submissions').get().n,3);pass('12 concurrent local attempts save exactly 3');
reset();const id=randomUUID();assert.equal((await route.POST(request({id}))).status,201);assert.equal((await route.POST(request({id}))).status,200);assert.equal(notified,1);const reply=await route.GET(new Request('https://example.test/api/questions?id='+id));assert.equal(reply.status,200);const data=await reply.json();assert.equal(data.status,"pending");assert(!('email' in data));assert(!('name' in data));assert.equal(reply.headers.get('X-Robots-Tag'),'noindex, nofollow');pass('Retry idempotency and private receipt excludes contacts/indexing');
reset();const payload="How handle <script>alert(1)</script> and '); DROP TABLE submissions; --";assert.equal((await route.POST(request({question:payload}))).status,201);assert.equal(sql.prepare('SELECT question FROM submissions').get().question,payload);assert(fs.readFileSync('public/ask.js','utf8').includes('.textContent=data.question'));pass('SQL payload stored as text; browser uses textContent');
let config={},calls=0;const human=load('lib/verify-human.ts',()=>({env:config}),{fetch:async()=>{calls++;return Response.json({success:true,hostname:'example.test',action:'submit-question'})}});
assert.equal(await human.verifyHuman(null,null,'example.test'),'ok');config.TURNSTILE_SITE_KEY='local-test';assert.equal(await human.verifyHuman('token',null,'example.test'),'unavailable');config.TURNSTILE_SECRET_KEY='local-only';assert.equal(await human.verifyHuman('',null,'example.test'),'rejected');assert.equal(await human.verifyHuman('token',null,'evil.test'),'rejected');assert.equal(await human.verifyHuman('token',null,'example.test'),'ok');pass('Prepared Turnstile verifies hostname and fails closed on partial configuration/missing token (mocked provider)');
let emailFetches=0;const mail=load('lib/notify-owner.ts',()=>({env:{MAIL_SEND_ENABLED:'false'}}),{fetch:async()=>{emailFetches++;throw Error()}});await mail.notifyOwner({id:randomUUID(),name:'QA',email:'qa@example.test',role:'project-manager',question:'Test only'},db);assert.equal(emailFetches,0);pass('Disabled email configuration makes no delivery request');
console.log(`${passed} test groups passed. Local SQLite and mocked providers only; no live inbox delivery, CAPTCHA or DDoS test.`);
})().catch(e=>{console.error(e);process.exitCode=1});
